### ISSUE TITLE
Requisition new `dibbs-vm` repository

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#123]
### Background
We need a new repo for our VM work! Let's get that party started, shall we?

### Action requested
Request a new `dibbs-vm` repo through the link in the CDCgov GH organization. The repository should be empty when created.

### Acceptance Criteria
The repo exists! Pretty easy, right?

### Additional context
N/A.

**Comment by alismx** [comment]
Amazing work! This looks complete to me.
