### ISSUE TITLE
Enable mandatory PR reviews and branch protection.

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#29]

**Comment by marycrawford** [comment]
@rin-skylight is it safe to assume the following Accepted Criteria:
1. the PR must be reviewed by one person on the Cloud Enablement Team;
2. the ticket number should be part of the branch name;
3. only special character of dashes are allowed in branch name;

Is there anything else?

**Comment by rin-skylight** [comment]
We're going to chat about this in our team chartering session! That's largely why this hasn't been filled out yet. Usually, we enforce a two-review policy. Branch names do not require ticket numbers; we prefer descriptive titles, and the numbers usually just promote clutter.

**Comment by rin-skylight** [comment]
Blocked until the completion of our chartering process.

**Comment by rin-skylight** [comment]
Preliminary branch protection was enforced at the beginning of Feb to protect the repository from potential vandalism. That setting will be revised pursuant to the completion of our team chartering exercises.

**Comment by rin-skylight** [comment]
Branch protection and PR policies have been implemented per the team chartering session on 24 April. Any changes can be made as needed.
