### ISSUE TITLE
Research needed elements for DIBBs cloud environment.

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#33]
### Background
To satisfy our OKRs for this quarter, we need to have an initial version of DIBBs in the shared Azure environment. We need a list of resources that their platform will require, so we can create tickets and plan accordingly.

### Action requested
To satisfy this ticket, please add comments with the following information:
* Number of K8S workloads and predicted specifications (mem, CPU, etc.), for sizing of cluster.
* Any necessary database allocations
* Required networking objects
* Application Gateway objects
* Ingress controllers
* Key Vaults
* Storage accounts/blob storage locations
* Any queues
* Any serverless functions

### Acceptance Criteria
1. This ticket is filled out with the proper information. The comments should be sufficient to use for generation of future tickets that will allow for the creation of the researched elements.

**Comment by kplaneaux** [comment]
@nickclyde suggested looking at DIBBs playground repo for code to reference

**Comment by rin-skylight** [comment]
https://github.com/CDCgov/phdi-playground/blob/main/terraform/implementation/main.tf

**Comment by marycrawford** [comment]
WIP [documentation](https://docs.google.com/document/d/1PYjAMwgUZvPMzkaSlnLG6GK5nE7ndcHnCFg_4l_jjzw/edit).

**Comment by marycrawford** [comment]
[Documentation](https://docs.google.com/document/d/1PYjAMwgUZvPMzkaSlnLG6GK5nE7ndcHnCFg_4l_jjzw/edit) was reviewed by team and finalized.
