### ISSUE TITLE
Create and deploy DIBBs AKS Cluster

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#39]
### Background
The pièce de résistance of our cloud enablement effort: the Azure Kubernetes instance for DIBBs. This will serve as the foundation for all future development.

### Action requested
Deploy a functional cluster that we can start getting workloads on!

### Acceptance Criteria
- TF exists for `dev` implementation of cluster
- Deployment action successfully deploys cluster

### Additional context
This item is dependent on the proper creation of the networking instances.

We should also use an [AGIC](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview) to set up proper ingress capability for this.

**Comment by marycrawford** [comment]
WIP [k8/aks template](https://github.com/CDCgov/dibbs-cloud/pull/57).
