### ISSUE TITLE
Create CI/CD deployment flow for Building Blocks components

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#46]
### Background
The home stretch! It's time to get the DIBBs components in the cloud. the VIPER set of components is half of our equation.

### Action requested
Work with the VIPER team to get their components deployed in the shared CDC cluster, along with updates to the team's release workflow to automatically deploy out to us.

### Acceptance Criteria
- All VIPEr workloads exist in our cluster
- Data processing pipeline behaves as expected

### Additional context
The CI/CD integration may be achieved through GH actions OR through Octopus Deploy. If we go with the former, we may want to create another ticket for the latter to keep track of that work.

This ticket may also need to be broken apart into separate smaller resources, depending on level of complexity. @nickclyde is our best expert on that facet.

**Comment by kplaneaux** [comment]
Need to decide whether we want to keep Helm integrated with terraform or decouple - design session needed!
