### ISSUE TITLE
Implement Trivy support on dibbs-aws repo

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#99]
### Background
We would like to ensure that Trivy is implemented on the AWS repo before we turn code over to STLTs.

### Acceptance Criteria
What needs to happen for this ticket to be complete?

**Comment by shanice-skylight** [comment]
Created this [PR](https://github.com/CDCgov/dibbs-aws/pull/4) to complete work

**Comment by shanice-skylight** [comment]
I think it would make sense to wait to merge it this Mary's PR is merged. Due to it scanning the terraform directory which is apart of that PR.

**Comment by rin-skylight** [comment]
This item needs to be merged prior to the large AWS PR. We're going to want to make sure that one has a full security scan performed on it, since it is going directly to customer partners. If that's not possible for some reason, we need to communicate that to the AWS folks so they can run a manual scan.

**Comment by shanice-skylight** [comment]
I added a [ticket](https://app.zenhub.com/workspaces/dibbs-cloud-enablement-659dde695f06770a91327bda/issues/gh/cdcgov/dibbs-cloud/101) to update the directory before we make it available for the customer

**Comment by shanice-skylight** [comment]
Ticket is now obsolete changes were made and merged
